server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5401/factory_db
    username: admin
    password: root
  liquibase:
    enabled: off
  jpa:
    hibernate:
      ddl-auto: validate
