--liquibase formatted sql

--changeset vikgonc:create_table_models
create table models
(
    id          bigint not null primary key generated by default as identity,
    name        varchar(100) not null,
    description varchar(255)
);
--rollback drop table models;
