--liquibase formatted sql

--changeset vikgonc:create_table_orders
create table orders
(
    id          bigint       not null primary key generated by default as identity,
    car_id      bigint       not null,
    status      varchar(100) not null,
    description varchar(255),
    foreign key (car_id)
        references cars (id)
);
--rollback drop table orders;
