--liquibase formatted sql

--changeset vikgonc:1
create table orders
(
    id     bigint not null primary key generated by default as identity,
    car_id bigint not null,
    status varchar(100) not null
);
--rollback drop table orders;
