server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5400/db
    username: admin
    password: root
  jpa:
    hibernate:
      ddl-auto: validate

kafka:
  bootstrap-server: localhost:9092
  consumer-group-id: order-group
  auto-offset-reset: earliest
  car-status-topic: car-status
  car-status-result-topic: car-status-result

grpc:
  port: 8888
